name: vklib
description: A simple vk library.
version: 0.1.2
author: Waitrum Evstegney Chachlyk <evstegneych@mail.ru>
homepage: https://github.com/Waitrum/VkLib
issue_tracker: https://github.com/Waitrum/VkLib/issues

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  http: ^0.13.1
  dotenv: ^3.0.0-nullsafety.0
  logger: ^1.0.0

dev_dependencies:
  test: ^1.14.4
