name: vklib
description: Simple framework for dart allows you to use the VK API easily.
version: 0.3.0
homepage: https://github.com/Waitrum/VkLib
issue_tracker: https://github.com/Waitrum/VkLib/issues

environment:
  sdk: '>=2.13.0 <3.0.0'

dependencies:
  http: ^0.13.1
  dotenv: ^3.0.0
#  logger: ^1.0.0

dev_dependencies:
  test: ^1.14.4
